### ISSUE TITLE
Feature request: Detect Leaky Vessels runtime vulnerability (CVE-2024-21626)

### ISSUE THREAD

**Issue by jedsalazar** [edera-dev/am-i-isolated#4]
Should be able to detect based on runc version

```
runc versions 1.1.11 and below, as used by containerization technologies such as Docker engine and Kubernetes, are vulnerable to an arbitrary file write vulnerability. Due to a file descriptor leak it is possible to mount the host file system with the permissions of runc (typically root). Successfully tested on Ubuntu 22.04 with runc 1.1.7-0ubuntu1~22.04.1 using Docker build.
```

**Comment by kaniini** [comment]
Unfortunately, we can't find reliable evidence in a container environment with runc 1.1.11, because of the nature of the vulnerability.  In essence, it uses `WORKDIR` to glitch the view of the filesystem so that the new container namespace's filesystem never gets fully entered.  We can't see any side effect of `WORKDIR` by the time the tool runs.
